baseURL: "https://franperic.github.io"
languageCode: "en-us"
title: Hello there!
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-PHGB9VX84Y

menu:
  main:
    - name: Posts
      url: posts
    - name: Talks
      url: talks

params:
  defaultTheme: light
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # TocSide: "left"
  ShowShareButtons: false
  dateFormat: "January 2, 2006"

  homeInfoParams:
    Title: "Welcome to My Website"
    Content: >
      Hello! I'm Fran Peric. Join me as I share my insights, experiences, and discoveries in Machine Learning.

  socialIcons:
    - name: github
      url: "https://github.com/franperic"
    - name: linkedin
      url: "https://linkedin.com/in/franperic"
    - name: twitter
      url: "https://twitter.com/fran_peric"
# markup:
#     goldmark:
#         renderer:
#             unsafe: true
#     highlight:
#         noClasses: false
#         # anchorLineNos: true
#         # codeFences: true
#         # guessSyntax: true
#         # lineNos: true
#         style: monokai
